### PR TITLE
Add support for WAV playback inside notebook cell

### PR DESCRIPTION
**Pull request by robinhad**
This pull request adds support for WAV playback inside notebook cell.

https://user-images.githubusercontent.com/5759207/109954272-d0f6ee00-7ce9-11eb-8b65-7297c1712897.mov

 It fixes https://github.com/microsoft/vscode-jupyter/issues/1012.

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Comment by DonJayamanne** [comment]
Thanks a lot @robinhad 
A lot of users have requested this feature.

The one concern I have with this is the fact that we will now always render HTML & not VS Code.
There are a few drawbacks to this (styles, custom commands, links, etc) - we're now going to have to own this as well.

Once again, thanks for this PR.

**Comment by DonJayamanne** [comment]
Starred a conversation here https://github.com/microsoft/vscode/issues/118275

**Comment by robinhad** [comment]
Thank you for your reply!
Only good alternative will be to build VSCode with some kind of "libre" ffmpeg - with only wav, ogg, vorbis for audio and AV1 for video.
It will facilitate the most common use cases for audio/video processing and will not bloat VSCode too much.

**Comment by khlevon** [comment]
Hi thanks for this PR.

Can someone review and merge this PR, please?

@rchiodo

**Comment by khlevon** [comment]
@robinhad  Can you please provide guide how can I use this patch like in beta mode in my workaround.

**Comment by rchiodo** [comment]
@robinhad if you wanted to ship this, you could make your own renderer extension for the 'text/html' mimetype.

**Pull request closed without merging**
