### PR TITLE
Remove hardcoded white background

### PR DESCRIPTION
**Pull request by mohtar**
Make background of .svgContent so that the rendered SVG (especially when `%config InlineBackend.figure_format = 'svg'` is enabled) works for any chosen background color for the editor.

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@mohtar 
Thanks the PR, Please could you file an issue on the https://github.com/microsoft/vscode-jupyter repo so we can review the issue first.

**Comment by mohtar** [comment]
Hmmm `src/client/index.css` is now deleted by this PR: https://github.com/microsoft/vscode-notebook-renderers/pull/59 What happened to it? Did it go to a different repo?

**Comment by mohtar** [comment]
Anyway, bug filed [here](https://github.com/microsoft/vscode-jupyter/issues/7590)

**Comment by DonJayamanne** [comment]
@mohtar Thanks for filing this issue. Its a duplicate of a few others filed by users.
We have fixed this, the PR you had wasn't the best fix, you can see the fix here https://github.com/microsoft/vscode-notebook-renderers/pull/64

Thanks for submitting a PR.
In the future ,please submit an issue when submitting a PR, then we can help with such items,

**Pull request merged**
