### PR TITLE
Add code review chat

### PR DESCRIPTION
**Pull request by lramos15**
Adds the code review chat script

### CODE REVIEW

**Review by DonJayamanne — APPROVED** [review]

**Comment by DonJayamanne** [comment]
Yeah, looks like some flakiness in the component governance azdo job.

**Comment by DonJayamanne** [comment]
Sorry I missed this.

**Review by DonJayamanne — APPROVED** [review]

**Comment by lramos15** [comment]
How can we merge when the test is failing?

**Comment by DonJayamanne** [comment]
> How can we merge when the test is failing?

I've re-run the Job, as suspected a flaky azure job (base SDL job was the culprit).
I've seen this in the past.

**Pull request merged**
