### PR TITLE
Bump plotly.js from 2.29.1 to 2.32.0

### PR DESCRIPTION
**Pull request by archmoj**
Thanks @bpasero @rchiodo for the review :pray:

cc: @ndrezn

### CODE REVIEW

**Review by ndrezn — APPROVED** [review]
Not a member of VSCode of course, but leaving a ✅ from Plotly team. This update allows some exciting new features (like z-ordering for traces in `v2.31.0`) in Plotly charts rendered in VSCode notebooks. Cheers & thanks VSCode team!

For reference here is the latest release: https://github.com/plotly/plotly.js/releases/tag/v2.32.0

**Comment by gvwilson** [comment]
hi @bpasero - any chance this one could be merged, or is further work required? (without this, Plotly in VSCode is restricted to a pretty old version). thanks - @gvwilson

**Comment by hannahker** [comment]
Tossing in my support for this PR! I rely on using VSCode notebooks for my work and would really like to use some of Plotly's new features.

**Comment by DonJayamanne** [comment]
Closing as cmopleted

**Comment by gvwilson** [comment]
Hi @DonJayamanne - you've marked this as "completed", but from what I can tell it hasn't actually been merged (or am I missing something)? It's a headache for our users. Thanks - @gvwilson cc @ndrezn

**Comment by ndrezn** [comment]
@gvwilson I see the change in: https://github.com/microsoft/vscode-notebook-renderers/pull/215

**Comment by gvwilson** [comment]
awesome - thank you @DonJayamanne

**Pull request closed without merging**
